version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring-net

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
    deploy:
      mode: global
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"  # 将外部端口更改为3001
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring-net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring-net

  pose-analysis-service:
    image: russellli/pose-analysis-service:latest
    ports:
      - "5000:5001"
    environment:
      MINIO_HOST: minio:9000
      MINIO_ROOT_USER: DefaultUser
      MINIO_ROOT_PASSWORD: DefaultPassword
    deploy:
      mode: global
      resources:
        limits:
          cpus: "2.0"
          memory: "1024M"
        reservations:
          cpus: "1.0"
          memory: "1024M"
    networks:
      - monitoring-net

  cleaning-robot-service:
    image: russellli/cleaning-robot-service:latest
    ports:
      - "5001:5000"
    deploy:
      mode: global
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    networks:
      - monitoring-net

  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: DefaultUser
      MINIO_ROOT_PASSWORD: DefaultPassword
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring-net

  web-frontend:
    image: russellli/web-frontend:latest
    ports:
      - "3000:3000"  # web-frontend 保持使用3000端口
    environment:
      API_URL: http://localhost:5000
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1.0"
          memory: "1024M"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    external: true

volumes:
  minio_data:

