version: '3.8'

services:
  minio:
    image: minio/minio:latest
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: DefaultUser
      MINIO_ROOT_PASSWORD: DefaultPassword
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  minio_data:
